name: Update data

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # run once a month

jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-data.txt
          pip install -r requirements-test.txt

      - name: Update data
        run: |
          python scripts/updatedata.py

      - name: Run pre-commit
        continue-on-error: true
        run: |
          pre-commit run --files src/codicefiscale/data/countries.json src/codicefiscale/data/municipalities.json

      - name: Commit data
        uses: test-room-7/action-update-file@v2
        with:
          file-path: |
            src/codicefiscale/data/countries.json
            src/codicefiscale/data/municipalities.json
          commit-msg: "Updated `countries.json` and/or `municipalities.json` data."
          committer-name: "Fabio Caccamo [bot]"
          committer-email: "fabio.caccamo@gmail.com"
          github-token: ${{ secrets.WORKFLOWS_UPDATE_DATA_TOKEN }}
